# Generated by Django 3.0.5 on 2020-04-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_post_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('money', models.PositiveSmallIntegerField()),
                ('number_of_card', models.PositiveSmallIntegerField(max_length=16, unique=True)),
            ],
        ),
    ]
