# Generated by Django 3.0.5 on 2020-04-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='money',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='number_of_card',
            field=models.PositiveIntegerField(max_length=16, unique=True),
        ),
    ]
