# Generated by Django 3.0.5 on 2020-04-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200423_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number_of_card',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
